In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')

In [6]:
df=pd.read_csv('..\\notebook\\data\\StudentsPerformance.csv')

In [8]:
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [9]:
df.shape

(1000, 8)

### data check to perform
#### missing values , duplicates , data type , unwanted columns , coloumn names , unique values of each column (remove unwanted values in column) , get stats of data , check various categories present in diff categorical columns

In [10]:
df.isna().sum()

gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
math score                     0
reading score                  0
writing score                  0
dtype: int64

In [14]:
df.duplicated().sum()

np.int64(0)

In [15]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   str
 1   race/ethnicity               1000 non-null   str
 2   parental level of education  1000 non-null   str
 3   lunch                        1000 non-null   str
 4   test preparation course      1000 non-null   str
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), str(5)
memory usage: 62.6 KB

In [17]:
df.nunique()

gender                          2
race/ethnicity                  5
parental level of education     6
lunch                           2
test preparation course         2
math score                     81
reading score                  72
writing score                  77
dtype: int64

In [18]:
print("gender :", df['gender'].value_counts())
print("race/ethnicity :", df['race/ethnicity'].value_counts())
print("parental level of education :", df['parental level of education'].value_counts())
print("lunch :", df['lunch'].value_counts())
print("test preparation course :", df['test preparation course'].value_counts())

gender : gender
female    518
male      482
Name: count, dtype: int64
race/ethnicity : race/ethnicity
group C    319
group D    262
group B    190
group E    140
group A     89
Name: count, dtype: int64
parental level of education : parental level of education
some college          226
associate's degree    222
high school           196
some high school      179
bachelor's degree     118
master's degree        59
Name: count, dtype: int64
lunch : lunch
standard        645
free/reduced    355
Name: count, dtype: int64
test preparation course : test preparation course
none         642
completed    358
Name: count, dtype: int64

In [19]:
df.describe()

       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

## Insight :
#### all means and sd are close to each other
#### there is min score of 0 for math , where as min score for other two are much higher , si min score of math might be outlier

In [28]:
# define numerical and categorical columns
numerical_cols = [col for col in df.columns if df[col].dtype in ['int64', 'float64']]
categorical_cols = [col for col in df.columns if df[col].dtype == 'str']

In [30]:
print("Numerical columns:", numerical_cols)
print("Number of numerical columns:", len(numerical_cols))
print("Categorical columns:", categorical_cols)
print("Number of categorical columns:", len(categorical_cols))

Numerical columns: ['math score', 'reading score', 'writing score']
Number of numerical columns: 3
Categorical columns: ['gender', 'race/ethnicity', 'parental level of education', 'lunch', 'test preparation course']
Number of categorical columns: 5

## Adding total score and avg score

In [ ]:
df['total_score'] = df['math score'] + df['reading score'] + df['writing score']
df['average_score'] = df['total_score'] / 3

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,total_score,average_score
0,female,group B,bachelor's degree,standard,none,72,72,74,218,72.666667
1,female,group C,some college,standard,completed,69,90,88,247,82.333333
2,female,group B,master's degree,standard,none,90,95,93,278,92.666667
3,male,group A,associate's degree,free/reduced,none,47,57,44,148,49.333333
4,male,group C,some college,standard,none,76,78,75,229,76.333333

In [35]:
df.to_csv('..\\notebook\\data\\StudentsPerformance_eda.csv', index=False)

In [ ]:
# create column transformer with three types of transformers :
num_features=